{% set name = "nosqlapi" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MatteoGuadrini/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e8b44d2a0ce691b401d03ff7bff0705edc01fcffd6214c9c02cc94e0652f3e68


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - nosqlapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MatteoGuadrini/nosqlapi
  doc_url: https://nosqlapi.rtfd.io/
  summary: A library for building standard NOSQL python libraries.
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
